name: Dart Lint

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: '3.5.2'
      - name: setup 
        run: |
          cd dart
          flutter pub get
      - name: run custom lint
        run: |
          cd dart
          dart run custom_lint
